# TLS certificate used for HTTPS connections.
# The certificate and private key are mounted into /certs.

tls:
  certificates:
    - certFile: /certs/atlas.crt
      keyFile: /certs/atlas.key


http:
  middlewares:
    security-headers:
      headers:
        # Enforce HTTPS for future requests
        stsSeconds: 31536000
        stsIncludeSubdomains: true

        # Prevent MIME type sniffing
        contentTypeNosniff: true

        # Protect against clickjacking
        frameDeny: true

        # Limit referrer information
        referrerPolicy: "strict-origin-when-cross-origin"